DEFAULT_DB_PATH = 'db.sqlite'
DEFAULT_MODEL_PATH = 'model.dill'
DEFAULT_RESULTS_PATH = 'predictions.csv'
DEFAULT_CONVERT_CHUNK_SIZE = 100
DEFAULT_PREDICT_CHUNK_SIZE = 10
DEFAULT_EXPORT_CHUNK_SIZE = 100
DEFAULT_NOW = '2017-10-17'
